blank_issues_enabled: false
contact_links:
  - name: 💬 General Discussion
    url: https://github.com/tedyfazrin/photobooth/discussions
    about: Ask questions, share ideas, or discuss the PhotoBooth app
  - name: 🔒 Security Vulnerability
    url: mailto:gmail@tedyfazrin.com
    about: Please report security vulnerabilities privately via email
  - name: 📧 Direct Contact
    url: mailto:gmail@tedyfazrin.com
    about: Contact the maintainer directly for other inquiries
