import { Template } from "@/components/template-selector";

export const templates: Template[] = [
  {
    id: '4x1',
    name: 'Classic Strip',
    size: '2" × 6"',
    aspectRatio: 1 / 3,
    orientation: 'portrait',
    photoCount: 4,
    layout: 'vertical',
    hasBorders: true,
    flattened: true,
  },
  {
    id: '3x1',
    name: 'Triple Strip',
    size: '2" × 4.5"',
    aspectRatio: 1 / 2.25,
    orientation: 'portrait',
    photoCount: 3,
    layout: 'vertical',
    hasBorders: true,
    flattened: true,
  },
  {
    id: '2x3',
    name: '2x3 Grid',
    size: '4" × 6"',
    aspectRatio: 2 / 3,
    orientation: 'portrait',
    photoCount: 6,
    layout: 'grid',
    hasBorders: true,
    flattened: true,
  },
  {
    id: '2x2',
    name: 'Grid 4x4',
    size: '4" × 4"',
    aspectRatio: 1,
    orientation: 'portrait',
    photoCount: 4,
    layout: 'grid',
    hasBorders: true,
    flattened: true,
  },
  {
    id: '1x1',
    name: 'Single Photo',
    size: '4" × 6"',
    aspectRatio: 2 / 3,
    orientation: 'landscape',
    photoCount: 1,
    layout: 'single',
    hasBorders: true,
    flattened: true,
  },
];